namespace StarBlue.Communication.Packets.Outgoing.Moderation
{
    internal class CfhTopicsInitComposer : MessageComposer
    {
        public CfhTopicsInitComposer() : base(Composers.CfhTopicsInitMessageComposer)
        {
        }

        public override void Compose(Composer packet)
        {
            packet.WriteInteger(6);
            packet.WriteString("sex_and_pii");
            packet.WriteInteger(8);
            packet.WriteString("sexual_webcam_images");
            packet.WriteInteger(1);
            packet.WriteString("mods");
            packet.WriteString("sexual_webcam_images_auto");
            packet.WriteInteger(2);
            packet.WriteString("mods");
            packet.WriteString("explicit_sexual_talk");
            packet.WriteInteger(3);
            packet.WriteString("mods");
            packet.WriteString("cybersex");
            packet.WriteInteger(4);
            packet.WriteString("mods");
            packet.WriteString("cybersex_auto");
            packet.WriteInteger(5);
            packet.WriteString("mods");
            packet.WriteString("meet_some");
            packet.WriteInteger(6);
            packet.WriteString("mods");
            packet.WriteString("meet_irl");
            packet.WriteInteger(7);
            packet.WriteString("mods");
            packet.WriteString("email_or_phone");
            packet.WriteInteger(8);
            packet.WriteString("mods");
            packet.WriteString("scamming");
            packet.WriteInteger(3);
            packet.WriteString("stealing");
            packet.WriteInteger(9);
            packet.WriteString("mods");
            packet.WriteString("scamsites");
            packet.WriteInteger(10);
            packet.WriteString("mods");
            packet.WriteString("selling_buying_accounts_or_furni");
            packet.WriteInteger(11);
            packet.WriteString("mods");
            packet.WriteString("trolling");
            packet.WriteInteger(11);
            packet.WriteString("hate_speech");
            packet.WriteInteger(12);
            packet.WriteString("mods");
            packet.WriteString("violent_roleplay");
            packet.WriteInteger(13);
            packet.WriteString("mods");
            packet.WriteString("swearing");
            packet.WriteInteger(14);
            packet.WriteString("auto_reply");
            packet.WriteString("drugs");
            packet.WriteInteger(15);
            packet.WriteString("mods");
            packet.WriteString("gambling");
            packet.WriteInteger(16);
            packet.WriteString("mods");
            packet.WriteString("self_threatening");
            packet.WriteInteger(17);
            packet.WriteString("mods");
            packet.WriteString("mild_staff_impersonation");
            packet.WriteInteger(18);
            packet.WriteString("mods");
            packet.WriteString("severe_staff_impersonation");
            packet.WriteInteger(19);
            packet.WriteString("mods");
            packet.WriteString("habbo_name");
            packet.WriteInteger(20);
            packet.WriteString("mods");
            packet.WriteString("minors_access");
            packet.WriteInteger(21);
            packet.WriteString("mods");
            packet.WriteString("bullying");
            packet.WriteInteger(22);
            packet.WriteString("guardians");
            packet.WriteString("interruption");
            packet.WriteInteger(2);
            packet.WriteString("flooding");
            packet.WriteInteger(23);
            packet.WriteString("mods");
            packet.WriteString("doors");
            packet.WriteInteger(24);
            packet.WriteString("mods");
            packet.WriteString("room");
            packet.WriteInteger(1);
            packet.WriteString("room_report");
            packet.WriteInteger(25);
            packet.WriteString("mods");
            packet.WriteString("help");
            packet.WriteInteger(2);
            packet.WriteString("help_habbo");
            packet.WriteInteger(26);
            packet.WriteString("auto_reply");
            packet.WriteString("help_payments");
            packet.WriteInteger(27);
            packet.WriteString("auto_reply");
        }
    }
}
